### ISSUE TITLE
A little Bug in OLED enclosure model.

### ISSUE THREAD

**Issue by onoma2** [jmamma/MegaCommand_Design#3]
Hello, there are not enough data in STL model for 3d printing the case.

![oled-bug](https://user-images.githubusercontent.com/22846785/55616692-0b248180-579b-11e9-81f4-17648f8c7a48.jpg)

**Comment by jmamma** [comment]
Hey Max,

I am assembling my 3d printer this weekend. I will investigate once it's set up.

Do you know the specific issue?

Cheers,

- Justin

**Comment by onoma2** [comment]
Missing points on the mesh. Please see screenshot attached.

**Comment by jmamma** [comment]
This was resolved. New model files uploaded some time ago
