### ISSUE TITLE
Alternative Chassis Design (migrated)

### ISSUE THREAD

**Issue by yatli** [jmamma/MegaCommand_Design#5]
I'm working on a metal chassis design.

Basically, I'd like to make it low-cost, durable and mountable. The current design consists of two parts, each can be produced with sheetmetal (304, 6061 etc.)

![image](https://user-images.githubusercontent.com/20684720/63641207-f1012680-c6dc-11e9-8c4d-3ed2aefb1685.png)

Potential problems:

The screw tap hole "ears" are less than optimal. May consider bend the whole edge instead of cutting those 6 ears.
Screen height?
No power switch hole...

**Comment by yatli** [comment]
The first batch has arrived. Lots of bugs, but I managed to fit it in:

![19-08-25 00-18-44 5915](https://user-images.githubusercontent.com/20684720/63641242-a03dfd80-c6dd-11e9-89b1-4b566dd0e00d.jpg)

![19-08-25 00-19-04 5916](https://user-images.githubusercontent.com/20684720/63641244-a338ee00-c6dd-11e9-8cdb-525c79d26da9.jpg)

![19-08-25 00-20-31 5917](https://user-images.githubusercontent.com/20684720/63641245-a6cc7500-c6dd-11e9-993b-78adff9f88d5.jpg)

**Comment by yatli** [comment]
== Problems ==

- [ ] The OLED Display window misaligns. It should be ~1mm left to the current position.
- [ ] The OLED Display window should be higher. Currently it mates very tightly with the metal case of the display.
- [ ] The left LED should be ~1mm left to the current position.
- [ ] Encoder through holes should be larger.
- [ ] Mount points is a joke -- one of them projects right onto the usb port!
- [ ] Key switch through holes should be larger.

**Comment by yatli** [comment]
The photo is different from the original design that the chassis tap drills are now all on the base plate.
The panel plate "envelopes" the base plate now.
The sheet metal flanges are also simplified to bring down the cost.
I've got 2 pairs at RMB 150 each.

**Comment by yatli** [comment]
Caveats:

1. Put insulation washers between the board and the copper standoffs. Otherwise it will short some pins.

2. Cut the washers so that the profile stays inside the pcb area:

![19-08-25 01-25-20 5919](https://user-images.githubusercontent.com/20684720/63641368-adf48280-c6df-11e9-9287-af2e32886399.jpg)

3. Tape the back of the panel around the OLED window. Otherwise it will short the display pins after assembly.

**Comment by jmamma** [comment]
Heavy Duty.

**Comment by yatli** [comment]
Yeah.
Full Metal Jacket.

edit: weighs a ton in hand!

**Comment by yatli** [comment]
Having a metal chasis is a bad idea. I almost fried something in MD when the rack mount screw contact with the MC metal chasis -- MD GND is -5V to USB GND, and a short of the two results in MD voltage dropping to 4V, which is very dangerous.
