### ISSUE TITLE
sram test fails 

### ISSUE THREAD

**Issue by frnktrpz** [jmamma/MegaCommand_Design#9]
Hi, opening this issue after asking for help over at elektronauts after running into some issues as a possible consequence of the (classic?) mistake of soldering the oled before the sd-card holder. 

Before desoldering the oled screen all test firmwares ran successfully. After desoldering the sram test fails instantly, led, sd-card and encoder/button tests all still successful. Ram test gives the following error:

>  Megank0 mismatch 
2200
MegaCommand SRAM Test
2200
SRAM Test Failed bank0 mismatch 
2200
 
Tried several times, tried reseating the board just in case but the same error occurs. 
Before replacing the ram it would be great if anyone could shed any light on other possible causes than a damaged/faulty ram chip.

Here are pictures of my build:   
![IMG_2447](https://user-images.githubusercontent.com/59180891/80897043-2858b600-8cf5-11ea-8061-38134b7c9793.jpg)
![IMG_2448](https://user-images.githubusercontent.com/59180891/80897045-2db60080-8cf5-11ea-85ff-0f67d8c4eb41.jpg)

**Comment by jmamma** [comment]
Can you take a clearer version of the bottom side of the board. i want to see the traces around the sram chip clearly

thanks

**Comment by frnktrpz** [comment]
Hope these are more useful: 

![IMG_2466](https://user-images.githubusercontent.com/59180891/80897445-f21d3580-8cf8-11ea-8791-4adfe1f30a8e.jpg)
![IMG_2471](https://user-images.githubusercontent.com/59180891/80897446-f34e6280-8cf8-11ea-9412-64fcabc1a9a1.jpg)

**Comment by jmamma** [comment]
I get the same test error when I attempt to run the SRAM test with the arduino disconnected from the main board.

This means theres a connectivity problem somewhere. 

```
Mest
2200

Failed bank0 zero reading
2200
MegaCommand SRAM Test
2200

Failed bank0 zero reading
2200
```

1)

For sanity, reconnect the Arduino and try again. Check that all the male header pins are aligned correctly with the Arduino when attaching it.

2)

Was the SRAM test working prior to the display problems?

3)

Can you make sure that there are no short circuits between solder joints. I see a few spots where there is a little bit of solder that might be causing a short between two unrelated pads.

4)

Do you own a multimeter?

Check that the SRAM chip is getting 5V. Pin32 connected to capacitor C4.
https://docs.rs-online.com/6fa1/0900766b8139de13.pdf

and check GND.

5)

The next step would be to verify the traces between the SRAM chip and the double row header. start with Power and GND and then work through the other traces. Keep a checklist. 

--

Troubleshooting may seem daunting, but it's a digital circuit and we can number down the possibilities by working systematically.

**Comment by frnktrpz** [comment]
> I get the same test error when I attempt to run the SRAM test with the arduino disconnected from the main board.
> 
> This means theres a connectivity problem somewhere.
> 
> ```
> Mest
> 2200
> 
> Failed bank0 zero reading
> 2200
> MegaCommand SRAM Test
> 2200
> 
> Failed bank0 zero reading
> 2200
> ```
> 
> 
> For sanity, reconnect the Arduino and try again. Check that all the male header pins are aligned correctly with the Arduino when attaching it.
> 
> 
> Was the SRAM test working prior to the display problems?
> 
> 
> Can you make sure that there are no short circuits between solder joints. I see a few spots where there is a little bit of solder that might be causing a short between two unrelated pads.
> 
> 
> Do you own a multimeter?
> 
> Check that the SRAM chip is getting 5V. Pin32 connected to capacitor C4.
> https://docs.rs-online.com/6fa1/0900766b8139de13.pdf
> 
> and check GND.
> 
> 
> The next step would be to verify the traces between the SRAM chip and the double row header. start with Power and GND and then work through the other traces. Keep a checklist.
> 
> --
> 
> Troubleshooting may seem daunting, but it's a digital circuit and we can number down the possibilities by working systematically.

Thank you for the amazing support, really appreciate it!
1. 
Headers appear to be aligned correctly, reseating the board doesn't seem to make a difference.
2.
Sram test was successful before desoldering the oled screen.
3.
Cleaning the board seems to have helped a bit as the test now runs for for a while before giving the error:
>2A00
SRAM Test Failed bank0 mismatch 
2A00

Test seems to fail at the same point each time. 
4.
If I measure voltage between the large GND on the MC pcb and pin 32 on the sram my multimeter indicates a short. 
5. 
I installed autodesk so I can systematically start working through the various test points. Will probably take me a while as I'm not used yet to navigating schematics.

**Comment by jmamma** [comment]
I can send you a screenshot of the top and bottom board traces.

**Comment by frnktrpz** [comment]
That would be great, thanks.

**Comment by jmamma** [comment]
[megacommand_1_0_2a12_top_bottom.pdf](https://github.com/jmamma/MegaCommand_Design/files/4570198/megacommand_1_0_2a12_top_bottom.pdf)

Viewed from top.

RED: top traces
BLUE: bottom traces.

**Comment by jmamma** [comment]
Can you measure voltage across the double header pins GND and 5V.

**Comment by frnktrpz** [comment]
I get around 4.5V reading across.   

edit;
Gave the board another clean and instantly got a bank0 read error, reconnected the usb cable and back to the initial bank0 mismatch error.
Not sure if relevant.

**Comment by jmamma** [comment]
I read 4.5V as well.

Now check GND (from double pin header) to the supply voltage of each chip

**Comment by jmamma** [comment]
> "edit;
> Gave the board another clean and instantly got a bank0 read error, reconnected the usb cable and back to the initial bank0 mismatch error.
> Not sure if relevant." 

can't really make any conclusions at this stage. 

If measuring voltages doesn't reveal anything unusual. Disconnect the arduino and start testing each trace. Start with connections from the double header to the SRAM chip.  Then the SRAM chip to the 74HC573 octal latch. 

It's getting late here. So i will check in the morning to see your progress.

**Comment by frnktrpz** [comment]
> I read 4.5V as well.
> 
> Now check GND (from double pin header) to the supply voltage of each chip

Consistently getting around 4.7 volts across. Except for the level shifter which shows around 3.3V.

> > "edit;
> > Gave the board another clean and instantly got a bank0 read error, reconnected the usb cable and back to the initial bank0 mismatch error.
> > Not sure if relevant."
> 
> can't really make any conclusions at this stage.
> 
> If measuring voltages doesn't reveal anything unusual. Disconnect the arduino and start testing each trace. Start with connections from the double header to the SRAM chip. Then the SRAM chip to the 74HC573 octal latch.
> 
> It's getting late here. So i will check in the morning to see your progress.

Ok, thanks again! Should keep me busy for a while. Have good night.

**Comment by frnktrpz** [comment]
I checked continuity for all the traces to/from the ram ic with my multimeter and was not able to find any fault. Didn't measure resistance, just checked the traces. 
All firmware tests besides the ram test (and the oled test, am unable to test now) run successfully. Is it safe to assume that the ram chip needs to be replaced or am I jumping the gun?

**Comment by jmamma** [comment]
My only other suggestion would be to re-flow the solder joints on the SRAM and octal latch. This would rule out a cold solder joint...

Another less scientific test would be to apply constant physical pressure to SRAM chip (with your thumb) and re-run the SRAM test. See if the test proceeds beyond 0x2200. This may reveal an intermittent connection...

Just be weary that desoldering the SRAM will be harder than removing the OLED. the pads are much smaller, and there is a high risk of stripping them from the board.

**Comment by yatli** [comment]
@frnktrpz also check the bank selection pin (PIN43)

You can enable the debug information in the test firmware, around line 57: https://github.com/jmamma/MegaCommand_Design/blob/3d7930fea5477b9c5ef57f928413bf8be208d8a9/TestFirmwares/megacommand_sram_test/megacommand_sram_test.ino#L57-L60

Uncomment these, and see if bank1 reading is correct but bank0 is not.

**Comment by jmamma** [comment]
@yatli If bank select is not working, then it should read/write to the same bank. 

Previously he was getting as far as 2A00

which is 2560 bytes.. I thought this may be indicative of an address line fault. But it doesn't line up with the addressing scheme.( It's been a while since I've looked at this. Maybe my interpretation is wrong.)

2^11 = 2048
2^10 = 1024
2^9 = 512

**Comment by yatli** [comment]
Ah, yes.
But I still recommend printing out the values -- if we get the same wrong value from both banks it means something (I'm not sure what it is yet)

**Comment by jmamma** [comment]
SRAM Test Failed bank0 mismatc

Yeah he's getting a mismatch. ~Which means the value read from bank 1 doesn't match the value read from bank 0.~

A static address line fault wouldn't cause this.
A static bank select  line fault wouldn't cause this.

**Comment by yatli** [comment]
The test FW doesn't compare bank1 read with bank0 read -- it compares both with the source random number, and when bank0 check fails, it doesn't report what's happening on bank1, just exit.

> which is 2560 bytes.. I thought this may be indicative of an address line fault. But it doesn't line up with the addressing scheme.( It's been a while since I've looked at this. Maybe my interpretation is wrong.)
> 
> 2^11 = 2048
> 2^10 = 1024
> 2^9 = 512

Hypothesis: 2^11 and 2^9 pins shorted?

**Comment by jmamma** [comment]
https://andybrown.me.uk/2011/08/28/512kb-sram-expansion-for-the-arduino-mega-design/

reference ^

**Comment by jmamma** [comment]
``` When choosing a latch we must ensure that it is fast enough to cope with the 16Mhz core clock of the Arduino. 74HC series latches are too slow. The datasheet recommends that we use the 74AHC series. ```

That's interesting.

**Comment by jmamma** [comment]
@yatli what type of latch are you using.

I'm running 74AHC series.

**Comment by yatli** [comment]
I've got `SN74HC573N`

**Comment by jmamma** [comment]
yeah I just checked a few of my boards. I have a mix of 74AH and 74H. Presumably if this was a problem it would have come up in my testing.

**Comment by yatli** [comment]
I didn't know the difference between HC and AHC. But I'm sure the LS series won't work here due to clocking limits. :)

**Comment by jmamma** [comment]
@frnktrpz please follow @yatli suggestion and uncomment the debug info from the SRAM test. 
Paste output here.

Cheers.

**Comment by frnktrpz** [comment]
I’ll do this after work tonight, thanks!

**Comment by frnktrpz** [comment]
> @frnktrpz please follow @yatli suggestion and uncomment the debug info from the SRAM test.
> Paste output here.
> 
> Cheers.

> MegaCommand SRAM Test
2200
114
0
0
Failed bank0 zero reading
2200

This is the result. Pressing on the ram seems to make no difference.

**Comment by jmamma** [comment]
And different from your first situation.

```
Megank0 mismatch
2200
MegaCommand SRAM Test
2200
SRAM Test Failed bank0 mismatch
2200
```

**Comment by frnktrpz** [comment]
Sorry, I was a bit unclear.

First ran the test while pressing on the ram, which resulted in the same outcome. Then ran the test again with lines 57-60 commented out, and that gave the quoted output.

**Comment by jmamma** [comment]
Yes. understood.

**Comment by jmamma** [comment]
<img width="572" alt="megacommand_sram" src="https://user-images.githubusercontent.com/8424097/81128696-3b81b500-8f85-11ea-95f3-772d99cb730c.png">

**Comment by jmamma** [comment]
Can you verify VCC and CE2 are 5V.

and VSS is GND

Measure from the top side of the boards on the legs of the chip (not the pads or solder).

CE2 is chip enable.

**Comment by frnktrpz** [comment]
Around 4.4V on both of those, measuring resistance between VSS and GND on the pcb gives something like 00.2 ohm. 

Have to go back to work in 5 hours so unfortunately won't be able to do any further checks until tomorrow.

**Comment by jmamma** [comment]
The SRAM test attempts to write a non zero value to the SRAM and then read it back.
It does this on both banks, and across all available memory addresses, starting at 0x2200.

If the read is zero, then the test fails.

```
2200
114
0
0
```

In your test, it tried to write the value 114 to memory position 0x2200 (the first memory address in the SRAM). When it reads it back it reads 0.

This means the data lines coming from the SRAM chip are all low.

114 in binary =  0b1110010
4 of the data lines should be high. 

--

SRAM Chip enable and supply voltage are correct.

Evidence suggests the SRAM chip is not working.

Edit: The other possibility is that the Octal latch is pulling down the Data lines to 0.

@yatli this is my conclusion. Do you have anything to add?

**Comment by jmamma** [comment]
Triple check WE and OE  (write enable, read enable) lines from SRAM and arduino double header.

**Comment by yatli** [comment]
One more thing to add, also check WE and RESET for 573. If reset is shorted, it will always give zero.

**Comment by jmamma** [comment]
output of 573 is only used for address lines. not data. so I dont suspect this is the fault.

**Comment by frnktrpz** [comment]
> Triple check WE and OE (write enable, read enable) lines from SRAM and arduino double header.

Cheers. Just got ready to check the traces one more time. Keep getting slightly different results each time I run the test, never gets very far but there's variance every time. Will check back in after this. 
Thanks again, really appreciate the support from you as well as yatli.

**Comment by frnktrpz** [comment]
Ok, it seems there is some bad connection going on after all. 
I re-checked the traces, each time a suspect connection came up it was either my poor handling of the probes or a topographical error and double/triple checking verified the connection. 

However one thing that I hadn't yet checked (for which I apologize, it didn't occur to me initially) were the double row headers between the Arduino and the MC board. A couple of the PA pins showed a way higher resistance value than the others. I used compressed air on the female headers and cleaned the pins with some alcohol. 
After reconnecting, the first 3 times the ram test results were the same as before. The fourth time it actually started going, but kept running way beyond 5 minutes and lines like this showed up:
>22
CA78
16
16
16
CA79
86
86
86
CA7A

Stopped the test after 15 minutes or so, reconnected the usb cable, ran the test again and it passed. Just ran it successfully for the second time. I'll run it again a couple of times tomorrow to be sure before re-soldering the oled screen...

**Comment by jmamma** [comment]
Great work.

> I'll run it again a couple of times tomorrow to be sure before re-soldering the oled screen

Best to be absolutely certain SRAM is working before moving on to the OLED.

Maybe give those pins a good soak in Isopropyl if you haven't already. 
You could reflow the double header solder joints as well, if you suspect cold solder.

**Comment by frnktrpz** [comment]
Reflowed some of the solderpoints on the double header and gave the board one more solid clean today after the ram test failing again this morning. After letting the board dry for a few hours I decided to solder a female header for the oled rather than soldering it on directly as I wasn't sure it was still in working condition after having gone through my desoldering treatment. Reconnected the board, ran the ramtest again, uploaded the firmware and:
![IMG_2552](https://user-images.githubusercontent.com/59180891/81436460-d63ae900-9169-11ea-81d5-59d6faa2c166.jpg)


Thanks again for the support jmamma and yatli, troubleshooting this with your help has been a great learning experience for me. Shoutout to micabeza as well for reaching out and offering help. Hope I'll be able to contribute a bit in the future. 
Cheers!

**Comment by jmamma** [comment]
Looking good. Well done for persevering.

**Comment by albadort76** [comment]
Hi, having a look on your pictures of the thread, I think your C7 electrolytic 10uf capacitor is not in the good orientation.

**Comment by frnktrpz** [comment]
> Hi, having a look on your pictures of the thread, I think your C7 electrolytic 10uf capacitor is not in the good orientation.

Haha, you are absolutely right. Didn't notice this until a few weeks ago while building a fresh MC because I wanted one that didn't have the oled screen misaligned because I decided to put it in some headers after my initial mishap. Regardless the MC operated normally for over a year. That's some solid circuit design.     

Sorry for necro'ing but I'm glad to be able to share this :-D
